export { default as Lesson1 } from './Lesson1.tsx';
export { default as Lesson2 } from './Lesson2.tsx';
export { default as Lesson3 } from './Lesson3.tsx';
export { default as Lesson4 } from './Lesson4.tsx';
export { default as Lesson5 } from './Lesson5.tsx';
export { default as Lesson6 } from './Lesson6.tsx';
export { default as Lesson7 } from './Lesson7.tsx';
export { default as Lesson8 } from './Lesson8.tsx';
export { default as Lesson9 } from './Lesson9.tsx';
